global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.

remote_write:
  - url: https://prometheus-prod-37-prod-ap-southeast-1.grafana.net/api/prom/push
    basic_auth:
      username: xxxx
      password: xxxx

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
      - targets: ["localhost:9090"]