services:
# Remove the nginx-proxy-manager service if running elsewhere
  nginx-proxy-manager:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    container_name: nginx-proxy-manager
    #network_mode: host
    #environment: # Uncomment this if IPv6 is not enabled on your host
    #  - DISABLE_IPV6=true # Uncomment this if IPv6 is not enabled on your hostt
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt