version: '3.9'
services:
  headscale:
    image: docker.io/headscale/headscale:latest
    restart: unless-stopped
    container_name: headscale
    networks:
      - headscale-net
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      # Please set <HEADSCALE_PATH> to the absolute path
      # of the previously created headscale directory.
      - /home/nmd2k/headscale/config:/etc/headscale
      - /home/nmd2k/headscale/lib:/var/lib/headscale
      - /home/nmd2k/headscale/run:/var/run/headscale
    command: serve

  headscale-ui:
    image: ghcr.io/gurucomputing/headscale-ui:latest
    pull_policy: always
    container_name: headscale-ui
    restart: unless-stopped
    networks:
      - headscale-net
    environment:
      - HEADSCALE_URL=http://headscale:8080
    ports:
       - "8443:8443"
       # Expose UI HTTP on an alternate host port for reverse proxying without TLS verification issues
       - "8082:8080"

networks:
  headscale-net:
    driver: bridge